name: Metrics
on:
  schedule: [{cron: "0 * * * *"}]
  push: {branches: ["master", "main"]}
  workflow_dispatch:
jobs:
  github-metrics:
    runs-on: ubuntu-latest
    steps:
      - uses: lowlighter/metrics@latest
        with:
          committer_token: ${{ secrets.GITHUB_TOKEN }}
          
          user: x7airworker
          template: classic
          base: header, repositories, metadata
          config_timezone: Europe/Berlin
          plugin_gists: yes
          plugin_languages: yes
          plugin_languages_colors: github
          plugin_languages_threshold: 0%
          plugin_lines: yes
          repositories_forks: yes
